<!--Zalogowano jako:-->
<!---->
<!---->
<?php
//    echo $this->get('login');
//    echo $this->get('man');
//?>
<!---->
<!--<a href="logout">Wyloguj</a>-->
<!--<br><br><br>-->


<!--<div class="col-md-3">-->

    <div class="col-md-3 well">
        <div class="well btn-group-lg">
            Zalogowano jako:
            <?php
                echo $this->get('login');
            ?>
            <br><br>

            <div class="well btn">
                <a href="logout">Wyloguj</a>
            </div>

<!--            <div class="btn-group-vertical">-->
<!---->
<!--                <button type="button" class="btn btn-primary">aaa</button>-->
<!--                <button type="button" class="btn btn-primary">aaaaaaa</button>-->
<!--                <button type="button" class="btn btn-primary">aaaa</button>-->
<!---->
<!--            </div>-->

            <div class="btn-group-vertical">
                <button type="button" class="btn btn-success" id="user">
                    Lista userów
                </button>

                <button type="button" class="btn btn-success" id="training">
                    Lista szkoleń
                </button>

                <button type="button" class="btn btn-success" id="trainer">
                    Lista prowadzących
                </button>

            </div>
<!--            <button type="button" class="well">-->
<!--                Lista userów-->
<!--            </button>-->
<!---->
<!--            <button type="button" class="well">-->
<!--                Lista szkoleń-->
<!--            </button>-->
<!---->
<!--            <button type="button" class="well">-->
<!--                Lista prowadzących-->
<!--            </button>-->

        </div>


    </div>
<!--</div>-->

<div class="col-md-9 panel panel-info" id="data_panel">


</div>

