
<div style="position: relative; height: 100%; width: 100%;">
    <div style="position: absolute">
        <div id="pole"></div>

        <div class="col-md-6 well">
            <div class="well btn-group-lg">
                <h5 class="h5">Zalogowano jako:
                <?php
                $ses = new \Zend\Session\Container('user_ses');
//                echo $ses->getManager()->getConfig()->getGcDivisor();
//                echo session_save_path();
//                echo "<br>". print_r(scandir(session_save_path()));
                echo $ses->username;
                ?></h5>
                <br><br>

                <div class="well btn">
                    <a href="logout">Wyloguj</a>
                </div>

                <!--            <div class="btn-group-vertical">-->
                <!---->
                <!--                <button type="button" class="btn btn-primary">aaa</button>-->
                <!--                <button type="button" class="btn btn-primary">aaaaaaa</button>-->
                <!--                <button type="button" class="btn btn-primary">aaaa</button>-->
                <!---->
                <!--            </div>-->

                <div class="btn-group-vertical">
        <!--            <button type="button" class="btn btn-success" id="user">-->
        <!--                Lista userów-->
        <!--            </button>-->

                </div>
                <!--            <button type="button" class="well">-->
                <!--                Lista userów-->
                <!--            </button>-->
                <!---->
                <!--            <button type="button" class="well">-->
                <!--                Lista szkoleń-->
                <!--            </button>-->
                <!---->
                <!--            <button type="button" class="well">-->
                <!--                Lista prowadzących-->
                <!--            </button>-->

            </div>
        </div>
        <!--</div>-->

        <div class="col-md-12 panel panel-info well" id="data_panel"></div>

        <div>
            <button id="rozdaj" type="button">Rozdaj</button>
            <div id="gracz" class="col-md-9 panel panel-info well">
        <!--        <img src="img/karty/A_cz.jpg" width="130" height="200">-->
        <!--        <img src="img/karty/A_cz.jpg" width="130" height="200">-->
        <!--        <img src="img/karty/A_cz.jpg" width="130" height="200">-->
        <!--        <img src="img/karty/A_cz.jpg" width="130" height="200">-->
            </div>
            <div id="data_panel"></div>
        </div>
    </div>
    <div id="info" style="position: absolute; height: 100%; width: 100%; background: #9acfea; top: 0px; z-index: -1">


    </div>
</div>



