<!--huj-->
<!---->
<?php
//echo $this->aaa;
//echo $this->get('dupa');
//echo $this->get('man');
//?>
<!---->
<!--<script type="text/javascript">-->
<!--    var getCookie = function(name) {-->
<!--        var cookies = document.cookie.split(';');-->
<!--        for(var i=0 ; i < cookies.length ; ++i) {-->
<!--            var pair = cookies[i].trim().split('=');-->
<!--            if(pair[0] == name)-->
<!--                return pair[1];-->
<!--        }-->
<!--        return null;-->
<!--    };-->
<!--</script>-->
