<?php

//echo $this->form($this->get('form'));

$form = $this->get('register_form');
$count = $form->count();
$i=0;

$form->prepare();
echo $this->form()->openTag($form);
foreach ($form as $element)
{
    if ($count == ++$i)
    {
        echo '<div class="form-group">';
            echo '<div class="row">';
                echo '<div class="col-sm-6 col-sm-offset-3">';
                    echo $this->formElement($element);
                echo '</div>';
            echo '</div>';
        echo '</div>';
    }
    elseif ($count-1 == $i)
    {
        echo '<div class="form-group text-center">';
        echo $this->formElement($element);
        echo '<label for="regulamin">Regulamin</label>';
        echo '</div>';

    }
    else
    {
        echo '<div class="form-group">';
        echo $this->formElement($element);
        echo '</div>';
    }
}
//echo $form->formLabel($form, $form->formText($form), 'append');
echo '<label id="test">test</label>';
echo $this->form()->closeTag($form);
?>



<!--<form id="register-form" action="" method="post" role="form" style="display: none;">-->
<!--    <div class="form-group">-->
<!--        <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <div class="row">-->
<!--            <div class="col-sm-6 col-sm-offset-3">-->
<!--                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Zarejestruj">-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</form>-->