<?php
//
//    echo $this->form($this->get('form'));
//    echo $this->get('logged');
//?>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Login</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Rejestracja</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">

                            <?php

                                $form = $this->get('form');
                                $count = $form->count();
                                $i=0;

                                $form->prepare();
                                echo $this->form()->openTag($form);
                                foreach ($form as $element)
                                {
                                    if ($count == ++$i)
                                    {
                                        echo '<div class="form-group">';
                                        echo '<div class="row">';
                                        echo '<div class="col-sm-6 col-sm-offset-3">';
//                                        echo '<div class="text-center">';
                                        echo $this->formElement($element);
                                        echo '</div>';
                                        echo '</div>';
//                                        echo '</div>';
                                        echo '</div>';
                                    }
                                    else
                                    {
                                        echo '<div class="form-group">';
                                        echo $this->formElement($element);
                                        echo '</div>';
                                    }
                                }
                                echo $this->form()->closeTag($form);

                            ?>


<!--                            <form id="login-form" action="login" method="post" role="form" style="display: block;">-->
<!--                                <div class="form-group">-->
<!--                                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">-->
<!--                                </div>-->
<!--                                <div class="form-group">-->
<!--                                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">-->
<!--                                </div>-->
<!--                                <div class="form-group text-center">-->
<!--                                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">-->
<!--                                    <label for="remember"> Zapamiętaj mnie</label>-->
<!--                                </div>-->
<!--                                <div class="form-group">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-sm-6 col-sm-offset-3">-->
<!--                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                <div class="form-group">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-lg-12">-->
<!--                                            <div class="text-center">-->
<!--                                                <a href="" tabindex="5" class="forgot-password">Zapomniałeś hasła?</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </form>-->


                            <?php
                            print $this->render('register.phtml');
//                            echo $this->partial('../registration/register.phtml');
//                            echo $this->partial('registration/register.phtml')
                            ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
